# Generated by Django 4.2.7 on 2023-12-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist_done',
            field=models.BooleanField(default=False),
        ),
    ]
