# Generated by Django 4.2.7 on 2023-12-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_wishlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
